server {
    listen       80;
    server_name  localhost;
    
    # Where your React files live inside the container
    root   /usr/share/nginx/html;
    index  index.html;

    # Standard routing for React/Vite
    location / {
        # This tells Nginx: "If the file exists, serve it. If not, route to index.html so React Router can handle it."
        try_files $uri $uri/ /index.html;
    }

    # Turn off logging for missing favicon and robots.txt (keeps logs clean!)
    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; allow all; }

    # The Security Block: Deny access to all hidden files (.git, .env, etc.)
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
    # Block WordPress-specific scanning instantly
    location ~* ^/(wp-admin|wp-includes|wp-content|wp-login\.php|xmlrpc\.php) {
        deny all;
        access_log off;
        log_not_found off;
    }
}